spring:
  datasource:
    url: jdbc:h2:file:./target/h2db/db/filmorateDB;DB_CLOSE_DELAY==1
#    username: user
#    password: 000000
    driver-class: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /h2

  flyway:
    url: jdbc:h2:file:./target/h2db/db/filmorateDB
#    schemas: public
    baseline-on-migrate: true

