spring:
  datasource:
    url: jdbc:h2:file:./db/filmorate;DATABASE_TO_LOWER=TRUE;
    username: sa
    password: password
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /h2

  flyway:
    url: jdbc:h2:file:./db/filmorate
#    schemas: public
    baseline-on-migrate: true
    user: sa
    password: password

